### ISSUE TITLE
Комментарии по БД и миграциям

### ISSUE THREAD

**Issue by SmileyTheSmile** [go-park-mail-ru/2024_1_TeaStealers#25]
### Схема
- Данные пользователя можно, но не обязательно вынести в отдельную таблицу Profile.
- То же самое с фотографиями во всех сущностях.
- Есть смысл не использовать enum для домов и квартир, а всё же держать их в отдельных таблицах и использовать Advert как таблицу для общих полей. Потом, когда вы будете брать все возможные объявления, вы будете делать запрос не к таблице advert, у которой не будет ссылок на таблицы домов и квартир, а именно к домам и квартирам, вместе с ними получая данные из Advert.
- date_creation нужна не во всех таблицах, во многих это избыток. Также, в некоторых она нужна, вроде houses, но её можно брать из связанных таблиц (building).
- В связующих таблицах отношений Many2Many не нужен id - у них PK - комбинация двух id связанных таблиц.

### Миграции
Миграции можно делать, создавая таблицы и тд в PGAdmin-e и затем смотреть их CREATE скрипты. Это кому как удобно.
- id стоит задавать через identity, пример:
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
- Имена полей должны быть в snake_case.
- Имена таблиц должны быть в единственном числе
- Не уверен в чём смысл UNIQUE(advertId, priority) в таблице image
- adress -> address, не думаю что будут придираться к грамматике, но на заметку.
- Когда замените UUID на Identity, можно будет убрать все id из тестовых данных и самим их не указывать нигде.

**Comment by SmileyTheSmile** [comment]
### Маркдаун
- Надо указать все поля таблиц, пояснять нужно только непонятные, но указать все.
- Форматирование странное, описания не должны быть заголовками.
- Для каждой таблицы нужно указать, что она удовлетворяет требуемым НФ. 
- Не у всех полей описание отделено тире, всё сливается вместе.
- Не указаны функциональные зависимости

**Comment by SmileyTheSmile** [comment]
### Миграции
- Почему таблица user зовется table_user? Не минус, просто странно.
- Есть пара полей, у которых дефолтом поставлены пустые строки или всякое такое, это как-бы лишает смысла существование null-ов. Если поле not null, пусть возвращается ошибка из-за нарушения ограничения, не нужен дефолт.
first_name TEXT CONSTRAINT first_name_length CHECK ( char_length(first_name) <= 127) NOT NULL DEFAULT ''
- По-моему стоит убрать default из image.priority - так может выйти, что у нескольких изображений одинаковый приоритет, если вам почему-то его не укажут.
- В advert_type таблицах и других смежных, комбинация двух id связанных таблиц - PK, а не UK.

### Маркдаун
- Стоит отделить части описаний про нормальные формы каким-то образом, например хедером.
- Зачем в static_view_advert дата создания?
- Описание is_deleted лучше поставить в начале файла, после схемы.

**Comment by ns-roxer** [comment]
1. таблицу user переименовать в user_data, чтобы избежать проблем с кавычками 
2. date_birthdate - тавтология, зачем префикс date, если атрибут типизированный? Убрать префикс
3. date_creation -> created_at переименовать везде
4. timestampt тип заменить на timestamptz везде. Привыкаем работать с таймзоной, даже если она "вот прямо сейчас" не используется

**Comment by vovangy** [comment]
Добрый день, исправил все пункты

**Comment by ns-roxer** [comment]
@SmileyTheSmile закрой, пожалуйста, issue
